export const FETCH_SEARCH_PRODUCT_REQUEST ='FETCH_SEARCH_PRODUCT_REQUEST'
export const FETCH_SEARCH_PRODUCT_SUCCESS ='FETCH_SEARCH_PRODUCT_SUCCESS'
export const FETCH_SEARCH_PRODUCT_FAILURE ='FETCH_SEARCH_PRODUCT_FAILURE'

export const SEARCH = 'SEARCH'